<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6pMjSaW\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6pMjSaW/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container6pMjSaW.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container6pMjSaW\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \Container6pMjSaW\App_KernelEnvDebugContainer([
    'container.build_hash' => '6pMjSaW',
    'container.build_id' => '5b8ec83a',
    'container.build_time' => 1714233628,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6pMjSaW');
