<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPjAoYxc\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPjAoYxc/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerPjAoYxc.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerPjAoYxc\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerPjAoYxc\App_KernelEnvDebugContainer([
    'container.build_hash' => 'PjAoYxc',
    'container.build_id' => 'd76bed72',
    'container.build_time' => 1714234932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPjAoYxc');
