<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtcviH8\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtcviH8/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerVtcviH8.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerVtcviH8\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerVtcviH8\App_KernelEnvDebugContainer([
    'container.build_hash' => 'VtcviH8',
    'container.build_id' => 'e544ae0c',
    'container.build_time' => 1714234111,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtcviH8');
