<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XCg5oFsService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.xCg5oFs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xCg5oFs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tipoNotificacion' => ['privates', '.errored..service_locator.xCg5oFs.App\\Entity\\TipoNotificacion', NULL, 'Cannot autowire service ".service_locator.xCg5oFs": it references class "App\\Entity\\TipoNotificacion" but no such service exists.'],
            'tipoNotificacionRepository' => ['privates', 'App\\Repository\\TipoNotificacionRepository', 'getTipoNotificacionRepositoryService', true],
        ], [
            'tipoNotificacion' => 'App\\Entity\\TipoNotificacion',
            'tipoNotificacionRepository' => 'App\\Repository\\TipoNotificacionRepository',
        ]);
    }
}
