<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RNmWH4NService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.rNmWH4N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rNmWH4N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
        ], [
            'empresaRepository' => 'App\\Repository\\EmpresaRepository',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
        ]);
    }
}
