<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UOOO1s7Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.uOOO1s7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOOO1s7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'amortizacionRepository' => ['privates', 'App\\Repository\\ProductoAmortizacionRepository', 'getProductoAmortizacionRepositoryService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'ventaProductoRepository' => ['privates', 'App\\Repository\\VentaProductoRepository', 'getVentaProductoRepositoryService', true],
        ], [
            'amortizacionRepository' => 'App\\Repository\\ProductoAmortizacionRepository',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'ventaProductoRepository' => 'App\\Repository\\VentaProductoRepository',
        ]);
    }
}
