<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gv52NgVService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.Gv52NgV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gv52NgV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.Gv52NgV.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Gv52NgV": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
