<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RkbDd3hService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.rkbDd3h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rkbDd3h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'westerunion' => ['privates', '.errored..service_locator.rkbDd3h.App\\Entity\\Westerunion', NULL, 'Cannot autowire service ".service_locator.rkbDd3h": it references class "App\\Entity\\Westerunion" but no such service exists.'],
        ], [
            'authenticationUtils' => '?',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'westerunion' => 'App\\Entity\\Westerunion',
        ]);
    }
}
