<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5jSpmYService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.5j_spmY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5j_spmY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'producto' => ['privates', '.errored..service_locator.5j_spmY.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.5j_spmY": it references class "App\\Entity\\Producto" but no such service exists.'],
            'productoAmortizacionRepository' => ['privates', 'App\\Repository\\ProductoAmortizacionRepository', 'getProductoAmortizacionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'producto' => 'App\\Entity\\Producto',
            'productoAmortizacionRepository' => 'App\\Repository\\ProductoAmortizacionRepository',
        ]);
    }
}
