<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZjK4SSQService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.ZjK4SSQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZjK4SSQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'paypal' => ['privates', '.errored..service_locator.ZjK4SSQ.App\\Entity\\Paypal', NULL, 'Cannot autowire service ".service_locator.ZjK4SSQ": it references class "App\\Entity\\Paypal" but no such service exists.'],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'paypal' => 'App\\Entity\\Paypal',
        ]);
    }
}
