<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EV2kq7aService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.EV2kq7a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EV2kq7a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'pagoRoyalAcumuladoRepository' => ['privates', 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository', 'getSolicitarPagoRoyalAcumuladoRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'solicitarPagoRoyalAcumuladoRepository' => ['privates', 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository', 'getSolicitarPagoRoyalAcumuladoRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'ventaRepository' => ['privates', 'App\\Repository\\VentaRepository', 'getVentaRepositoryService', true],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'pagoRoyalAcumuladoRepository' => 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'solicitarPagoRoyalAcumuladoRepository' => 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'ventaRepository' => 'App\\Repository\\VentaRepository',
        ]);
    }
}
