<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VJqzWAJService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.VJqzWAJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VJqzWAJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'venta' => ['privates', '.errored..service_locator.VJqzWAJ.App\\Entity\\Venta', NULL, 'Cannot autowire service ".service_locator.VJqzWAJ": it references class "App\\Entity\\Venta" but no such service exists.'],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'venta' => 'App\\Entity\\Venta',
        ]);
    }
}
