<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X8onDfMService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.x8onDfM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x8onDfM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bizum' => ['privates', '.errored..service_locator.x8onDfM.App\\Entity\\Bizum', NULL, 'Cannot autowire service ".service_locator.x8onDfM": it references class "App\\Entity\\Bizum" but no such service exists.'],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
        ], [
            'bizum' => 'App\\Entity\\Bizum',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
        ]);
    }
}
