<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBizum2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.x8onDfM.App\Entity\Bizum' shared service.
     *
     * @return \App\Entity\Bizum
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.x8onDfM": it references class "App\\Entity\\Bizum" but no such service exists.');
    }
}
