<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresa3Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wi_j08R.App\Entity\Empresa' shared service.
     *
     * @return \App\Entity\Empresa
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wi_j08R": it references class "App\\Entity\\Empresa" but no such service exists.');
    }
}
