<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSolicitarRecogidaService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8KCS48g.App\Entity\SolicitarRecogida' shared service.
     *
     * @return \App\Entity\SolicitarRecogida
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8KCS48g": it references class "App\\Entity\\SolicitarRecogida" but no such service exists.');
    }
}
