<?php

namespace ContainerVtcviH8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWesterunionService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0OY5jfu.App\Entity\Westerunion' shared service.
     *
     * @return \App\Entity\Westerunion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0OY5jfu": it references class "App\\Entity\\Westerunion" but no such service exists.');
    }
}
