<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZWpvUwRService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.ZWpvUwR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZWpvUwR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bizumRepository' => ['privates', 'App\\Repository\\BizumRepository', 'getBizumRepositoryService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'paypalRepository' => ['privates', 'App\\Repository\\PaypalRepository', 'getPaypalRepositoryService', true],
            'transferenciaBancariaRepository' => ['privates', 'App\\Repository\\TransferenciaBancariaRepository', 'getTransferenciaBancariaRepositoryService', true],
            'westerunionRepository' => ['privates', 'App\\Repository\\WesterunionRepository', 'getWesterunionRepositoryService', true],
        ], [
            'bizumRepository' => 'App\\Repository\\BizumRepository',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'paypalRepository' => 'App\\Repository\\PaypalRepository',
            'transferenciaBancariaRepository' => 'App\\Repository\\TransferenciaBancariaRepository',
            'westerunionRepository' => 'App\\Repository\\WesterunionRepository',
        ]);
    }
}
