<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EksB6sdService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.EksB6sd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EksB6sd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transferenciaBancariaRepository' => ['privates', 'App\\Repository\\TransferenciaBancariaRepository', 'getTransferenciaBancariaRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'transferenciaBancariaRepository' => 'App\\Repository\\TransferenciaBancariaRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
