<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YKxaqkvService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.yKxaqkv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yKxaqkv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'solicitarPagoRoyalAcumuladoRepository' => ['privates', 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository', 'getSolicitarPagoRoyalAcumuladoRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'solicitarPagoRoyalAcumuladoRepository' => 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
