<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4K6UnPNService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.4K6UnPN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4K6UnPN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pdf' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'producto' => ['privates', '.errored..service_locator.4K6UnPN.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.4K6UnPN": it references class "App\\Entity\\Producto" but no such service exists.'],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'pdf' => 'App\\Service\\PdfService',
            'producto' => 'App\\Entity\\Producto',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
