<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAyuda3Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kumnpdQ.App\Entity\Ayuda' shared service.
     *
     * @return \App\Entity\Ayuda
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kumnpdQ": it references class "App\\Entity\\Ayuda" but no such service exists.');
    }
}
