<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBizumService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aG6BVd1.App\Entity\Bizum' shared service.
     *
     * @return \App\Entity\Bizum
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aG6BVd1": it references class "App\\Entity\\Bizum" but no such service exists.');
    }
}
