<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.V3B.HPO.App\Entity\Pack' shared service.
     *
     * @return \App\Entity\Pack
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.V3B.HPO": it references class "App\\Entity\\Pack" but no such service exists.');
    }
}
