<?php

namespace Container6pMjSaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser3Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S0Dl95W.App\Entity\User' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S0Dl95W": it references class "App\\Entity\\User" but no such service exists.');
    }
}
