<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WiJ08RService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.wi_j08R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wi_j08R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empresa' => ['privates', '.errored..service_locator.wi_j08R.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.wi_j08R": it references class "App\\Entity\\Empresa" but no such service exists.'],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
        ]);
    }
}
