<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LViM5rqService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.lViM5rq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lViM5rq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pdf' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'pdf' => 'App\\Service\\PdfService',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
