<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0OY5jfuService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.0OY5jfu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0OY5jfu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'westerunion' => ['privates', '.errored..service_locator.0OY5jfu.App\\Entity\\Westerunion', NULL, 'Cannot autowire service ".service_locator.0OY5jfu": it references class "App\\Entity\\Westerunion" but no such service exists.'],
            'westerunionRepository' => ['privates', 'App\\Repository\\WesterunionRepository', 'getWesterunionRepositoryService', true],
        ], [
            'westerunion' => 'App\\Entity\\Westerunion',
            'westerunionRepository' => 'App\\Repository\\WesterunionRepository',
        ]);
    }
}
