<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LtTDIVRService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.LtTDIVR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LtTDIVR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empresa' => ['privates', '.errored..service_locator.LtTDIVR.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.LtTDIVR": it references class "App\\Entity\\Empresa" but no such service exists.'],
            'empresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
            'empresaRepository' => 'App\\Repository\\EmpresaRepository',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
        ]);
    }
}
