<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V3B_HPOService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.V3B.HPO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V3B.HPO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'pack' => ['privates', '.errored..service_locator.V3B.HPO.App\\Entity\\Pack', NULL, 'Cannot autowire service ".service_locator.V3B.HPO": it references class "App\\Entity\\Pack" but no such service exists.'],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'pack' => 'App\\Entity\\Pack',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
