<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8KCS48gService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.8KCS48g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8KCS48g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'solicitar' => ['privates', '.errored..service_locator.8KCS48g.App\\Entity\\SolicitarRecogida', NULL, 'Cannot autowire service ".service_locator.8KCS48g": it references class "App\\Entity\\SolicitarRecogida" but no such service exists.'],
            'tipoNotificacionRepository' => ['privates', 'App\\Repository\\TipoNotificacionRepository', 'getTipoNotificacionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'solicitar' => 'App\\Entity\\SolicitarRecogida',
            'tipoNotificacionRepository' => 'App\\Repository\\TipoNotificacionRepository',
        ]);
    }
}
