<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P9GznPwService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.P9GznPw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P9GznPw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'solicitarPagoRoyalAcumulado' => ['privates', '.errored..service_locator.P9GznPw.App\\Entity\\SolicitarPagoRoyalAcumulado', NULL, 'Cannot autowire service ".service_locator.P9GznPw": it references class "App\\Entity\\SolicitarPagoRoyalAcumulado" but no such service exists.'],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'solicitarPagoRoyalAcumulado' => 'App\\Entity\\SolicitarPagoRoyalAcumulado',
        ]);
    }
}
