<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AG6BVd1Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.aG6BVd1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aG6BVd1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bizum' => ['privates', '.errored..service_locator.aG6BVd1.App\\Entity\\Bizum', NULL, 'Cannot autowire service ".service_locator.aG6BVd1": it references class "App\\Entity\\Bizum" but no such service exists.'],
            'bizumRepository' => ['privates', 'App\\Repository\\BizumRepository', 'getBizumRepositoryService', true],
        ], [
            'bizum' => 'App\\Entity\\Bizum',
            'bizumRepository' => 'App\\Repository\\BizumRepository',
        ]);
    }
}
