<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHUuStzService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.iHUuStz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHUuStz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paypal' => ['privates', '.errored..service_locator.iHUuStz.App\\Entity\\Paypal', NULL, 'Cannot autowire service ".service_locator.iHUuStz": it references class "App\\Entity\\Paypal" but no such service exists.'],
            'paypalRepository' => ['privates', 'App\\Repository\\PaypalRepository', 'getPaypalRepositoryService', true],
        ], [
            'paypal' => 'App\\Entity\\Paypal',
            'paypalRepository' => 'App\\Repository\\PaypalRepository',
        ]);
    }
}
