<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaypal2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iHUuStz.App\Entity\Paypal' shared service.
     *
     * @return \App\Entity\Paypal
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iHUuStz": it references class "App\\Entity\\Paypal" but no such service exists.');
    }
}
