<?php

namespace ContainerPjAoYxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVentaService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VJqzWAJ.App\Entity\Venta' shared service.
     *
     * @return \App\Entity\Venta
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VJqzWAJ": it references class "App\\Entity\\Venta" but no such service exists.');
    }
}
