<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Es3F9IoService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.Es3F9Io' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Es3F9Io'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ayuda' => ['privates', '.errored..service_locator.Es3F9Io.App\\Entity\\Ayuda', NULL, 'Cannot autowire service ".service_locator.Es3F9Io": it references class "App\\Entity\\Ayuda" but no such service exists.'],
            'ayudaRepository' => ['privates', 'App\\Repository\\AyudaRepository', 'getAyudaRepositoryService', true],
        ], [
            'ayuda' => 'App\\Entity\\Ayuda',
            'ayudaRepository' => 'App\\Repository\\AyudaRepository',
        ]);
    }
}
