<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQ08SwFService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.nQ08SwF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nQ08SwF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'transferenciaBancarium' => ['privates', '.errored..service_locator.nQ08SwF.App\\Entity\\TransferenciaBancaria', NULL, 'Cannot autowire service ".service_locator.nQ08SwF": it references class "App\\Entity\\TransferenciaBancaria" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'authenticationUtils' => '?',
            'transferenciaBancarium' => 'App\\Entity\\TransferenciaBancaria',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
