<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EuMjxUxService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.EuMjxUx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EuMjxUx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'servicio' => ['privates', '.errored..service_locator.EuMjxUx.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.EuMjxUx": it references class "App\\Entity\\Producto" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'servicio' => 'App\\Entity\\Producto',
        ]);
    }
}
