<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4FzKp2xService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.4FzKp2x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4FzKp2x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bizumRepository' => ['privates', 'App\\Repository\\BizumRepository', 'getBizumRepositoryService', true],
            'empresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'paypalRepository' => ['privates', 'App\\Repository\\PaypalRepository', 'getPaypalRepositoryService', true],
            'solicitarPagoRoyalAcumuladoRepository' => ['privates', 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository', 'getSolicitarPagoRoyalAcumuladoRepositoryService', true],
            'transferenciaBancariaRepository' => ['privates', 'App\\Repository\\TransferenciaBancariaRepository', 'getTransferenciaBancariaRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'westerunionRepository' => ['privates', 'App\\Repository\\WesterunionRepository', 'getWesterunionRepositoryService', true],
        ], [
            'bizumRepository' => 'App\\Repository\\BizumRepository',
            'empresaRepository' => 'App\\Repository\\EmpresaRepository',
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'paypalRepository' => 'App\\Repository\\PaypalRepository',
            'solicitarPagoRoyalAcumuladoRepository' => 'App\\Repository\\SolicitarPagoRoyalAcumuladoRepository',
            'transferenciaBancariaRepository' => 'App\\Repository\\TransferenciaBancariaRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'westerunionRepository' => 'App\\Repository\\WesterunionRepository',
        ]);
    }
}
