<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A7n0s25Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.A7n0s25' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A7n0s25'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificacionRepository' => ['privates', 'App\\Repository\\NotificacionRepository', 'getNotificacionRepositoryService', true],
            'tipoNotificacion' => ['privates', '.errored..service_locator.A7n0s25.App\\Entity\\TipoNotificacion', NULL, 'Cannot autowire service ".service_locator.A7n0s25": it references class "App\\Entity\\TipoNotificacion" but no such service exists.'],
            'tipoNotificacionRepository' => ['privates', 'App\\Repository\\TipoNotificacionRepository', 'getTipoNotificacionRepositoryService', true],
        ], [
            'notificacionRepository' => 'App\\Repository\\NotificacionRepository',
            'tipoNotificacion' => 'App\\Entity\\TipoNotificacion',
            'tipoNotificacionRepository' => 'App\\Repository\\TipoNotificacionRepository',
        ]);
    }
}
