<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KumnpdQService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.kumnpdQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kumnpdQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ayuda' => ['privates', '.errored..service_locator.kumnpdQ.App\\Entity\\Ayuda', NULL, 'Cannot autowire service ".service_locator.kumnpdQ": it references class "App\\Entity\\Ayuda" but no such service exists.'],
        ], [
            'ayuda' => 'App\\Entity\\Ayuda',
        ]);
    }
}
