<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UH3TI4pService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.UH3TI4p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UH3TI4p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bizumRepository' => ['privates', 'App\\Repository\\BizumRepository', 'getBizumRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'bizumRepository' => 'App\\Repository\\BizumRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
