<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSolicitarPagoRoyalAcumulado3Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gwK3ln5.App\Entity\SolicitarPagoRoyalAcumulado' shared service.
     *
     * @return \App\Entity\SolicitarPagoRoyalAcumulado
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gwK3ln5": it references class "App\\Entity\\SolicitarPagoRoyalAcumulado" but no such service exists.');
    }
}
