<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransferenciaBancaria2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nQ08SwF.App\Entity\TransferenciaBancaria' shared service.
     *
     * @return \App\Entity\TransferenciaBancaria
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nQ08SwF": it references class "App\\Entity\\TransferenciaBancaria" but no such service exists.');
    }
}
