<?php

namespace ContainerTxHd3fm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTipoNotificacion2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.skAhvWD.App\Entity\TipoNotificacion' shared service.
     *
     * @return \App\Entity\TipoNotificacion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.skAhvWD": it references class "App\\Entity\\TipoNotificacion" but no such service exists.');
    }
}
