<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \App\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'beneficioxventa', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'tipodemoneda', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'idd', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'stockAdvertencia', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'tipoProducto', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'conceptoServicio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'descripcionServicio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'documentoServicio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'ventas', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'ventasCanceladas', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'notificaciones', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'amortizaciones', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'packs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'beneficioxventa', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'tipodemoneda', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'idd', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'stockAdvertencia', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'tipoProducto', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'conceptoServicio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'descripcionServicio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'documentoServicio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'ventas', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'ventasCanceladas', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'notificaciones', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'amortizaciones', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'packs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(?string $nombre): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen(?string $imagen): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeneficioxventa(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeneficioxventa', []);

        return parent::getBeneficioxventa();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeneficioxventa(?string $beneficioxventa): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeneficioxventa', [$beneficioxventa]);

        return parent::setBeneficioxventa($beneficioxventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipodemoneda(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipodemoneda', []);

        return parent::getTipodemoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipodemoneda(?string $tipodemoneda): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipodemoneda', [$tipodemoneda]);

        return parent::setTipodemoneda($tipodemoneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdd(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdd', []);

        return parent::getIdd();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdd(?string $idd): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdd', [$idd]);

        return parent::setIdd($idd);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock(?int $stock): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockAdvertencia(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockAdvertencia', []);

        return parent::getStockAdvertencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockAdvertencia(int $stockAdvertencia): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockAdvertencia', [$stockAdvertencia]);

        return parent::setStockAdvertencia($stockAdvertencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoProducto(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoProducto', []);

        return parent::getTipoProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoProducto(int $tipoProducto): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoProducto', [$tipoProducto]);

        return parent::setTipoProducto($tipoProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getConceptoServicio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConceptoServicio', []);

        return parent::getConceptoServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setConceptoServicio(?string $conceptoServicio): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConceptoServicio', [$conceptoServicio]);

        return parent::setConceptoServicio($conceptoServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionServicio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionServicio', []);

        return parent::getDescripcionServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionServicio(?string $descripcionServicio): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionServicio', [$descripcionServicio]);

        return parent::setDescripcionServicio($descripcionServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoServicio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoServicio', []);

        return parent::getDocumentoServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoServicio(?string $documentoServicio): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoServicio', [$documentoServicio]);

        return parent::setDocumentoServicio($documentoServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentas', []);

        return parent::getVentas();
    }

    /**
     * {@inheritDoc}
     */
    public function addVenta(\App\Entity\VentaProducto $venta): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVenta', [$venta]);

        return parent::addVenta($venta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVenta(\App\Entity\VentaProducto $venta): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVenta', [$venta]);

        return parent::removeVenta($venta);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentasCanceladas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentasCanceladas', []);

        return parent::getVentasCanceladas();
    }

    /**
     * {@inheritDoc}
     */
    public function addVentaCancelada(\App\Entity\VentaCancelada $ventaCancelada): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVentaCancelada', [$ventaCancelada]);

        return parent::addVentaCancelada($ventaCancelada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVentaCancelada(\App\Entity\VentaCancelada $ventaCancelada): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVentaCancelada', [$ventaCancelada]);

        return parent::removeVentaCancelada($ventaCancelada);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificaciones', []);

        return parent::getNotificaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotificaciones(\App\Entity\Notificacion $notificaciones): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotificaciones', [$notificaciones]);

        return parent::addNotificaciones($notificaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotificaciones(\App\Entity\Notificacion $notificaciones): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotificaciones', [$notificaciones]);

        return parent::removeNotificaciones($notificaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmortizaciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmortizaciones', []);

        return parent::getAmortizaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function addAmortizaciones(\App\Entity\ProductoAmortizacion $amortizaciones): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAmortizaciones', [$amortizaciones]);

        return parent::addAmortizaciones($amortizaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAmortizaciones(\App\Entity\ProductoAmortizacion $amortizaciones): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAmortizaciones', [$amortizaciones]);

        return parent::removeAmortizaciones($amortizaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function cantidadVentas(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cantidadVentas', []);

        return parent::cantidadVentas();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getPacks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPacks', []);

        return parent::getPacks();
    }

    /**
     * {@inheritDoc}
     */
    public function addPacks(\App\Entity\PackProducto $packs): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPacks', [$packs]);

        return parent::addPacks($packs);
    }

    /**
     * {@inheritDoc}
     */
    public function removePacks(\App\Entity\PackProducto $packs): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePacks', [$packs]);

        return parent::removePacks($packs);
    }

}
